# Generated by Django 5.1.1 on 2024-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('no_empleado', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_agente', models.CharField(max_length=50)),
                ('apellido_agente', models.CharField(max_length=50)),
                ('telefono_ext', models.CharField(max_length=12)),
                ('email_agente', models.EmailField(max_length=75)),
                ('ubicacion_area', models.CharField(max_length=25)),
                ('fecha_contratacion', models.DateField()),
            ],
        ),
    ]
