# Generated by Django 5.1.1 on 2024-10-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poliza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('monto_pago_recurrente', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=25)),
                ('fecha_pago', models.DateField()),
                ('descrip_pago', models.CharField(max_length=125)),
                ('no_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poliza.poliza')),
            ],
        ),
    ]
