# Generated by Django 5.1.1 on 2024-10-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poliza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id_siniestro', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha_siniestro', models.DateField()),
                ('tipo_siniestro', models.CharField(max_length=35)),
                ('descripcion_siniestro', models.CharField(max_length=150)),
                ('monto_estimado', models.FloatField()),
                ('no_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poliza.poliza')),
            ],
        ),
    ]
