# Generated by Django 5.1.1 on 2024-10-01 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agente', '0001_initial'),
        ('gestion_clientes', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('no_poliza', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
                ('fecha_fin', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('monto_asegurado', models.FloatField()),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.cliente')),
                ('no_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.agente')),
                ('producto_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
            ],
        ),
    ]
