# Generated by Django 5.1.1 on 2024-10-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poliza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('no_incidente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha_incidente', models.DateField()),
                ('descripcion_r', models.CharField(max_length=100)),
                ('monto_reclamo', models.FloatField()),
                ('estado_reclamo', models.CharField(max_length=15)),
                ('no_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poliza.poliza')),
            ],
        ),
    ]
